export const CATEGORIES = [
  { id: 'all', label: 'Todo' },
  { id: 'novel', label: 'Novelas' },
  { id: 'bachman', label: 'Bachman' },
  { id: 'dark-tower', label: 'La Torre Oscura' },
  { id: 'collections', label: 'Cuentos' },
  { id: 'nonfiction', label: 'No Ficción' },
  { id: 'bill-hodges', label: 'Trilogía Bill Hodges' },
  { id: 'gwendy', label: 'Trilogía Gwendy' },
  { id: 'talisman', label: 'El Talismán' },
]

export const BOOKS = [
  // Novelas
  { id: 'carrie',                       title: 'Carrie',                              titleEs: 'Carrie',                                  year: 1974, category: 'novel' },
  { id: 'salems-lot',                   title: "'Salem's Lot",                        titleEs: "El misterio de Salem's Lot",              year: 1975, category: 'novel' },
  { id: 'the-shining',                  title: 'The Shining',                         titleEs: 'El resplandor',                           year: 1977, category: 'novel' },
  { id: 'the-stand',                    title: 'The Stand',                           titleEs: 'Apocalipsis',                             year: 1978, category: 'novel' },
  { id: 'the-dead-zone',                title: 'The Dead Zone',                       titleEs: 'La zona muerta',                          year: 1979, category: 'novel' },
  { id: 'firestarter',                  title: 'Firestarter',                         titleEs: 'Ojos de fuego',                           year: 1980, category: 'novel' },
  { id: 'cujo',                         title: 'Cujo',                                titleEs: 'Cujo',                                    year: 1981, category: 'novel' },
  { id: 'christine',                    title: 'Christine',                           titleEs: 'Christine',                               year: 1983, category: 'novel' },
  { id: 'pet-sematary',                 title: 'Pet Sematary',                        titleEs: 'Cementerio de animales',                  year: 1983, category: 'novel' },
  { id: 'cycle-of-the-werewolf',        title: 'Cycle of the Werewolf',               titleEs: 'El ciclo del hombre lobo',                year: 1983, category: 'novel' },
  { id: 'the-eyes-of-the-dragon',       title: 'The Eyes of the Dragon',              titleEs: 'Los ojos del dragón',                     year: 1984, category: 'novel' },
  { id: 'it',                           title: 'It',                                  titleEs: 'Eso',                                     year: 1986, category: 'novel' },
  { id: 'misery',                       title: 'Misery',                              titleEs: 'Misery',                                  year: 1987, category: 'novel' },
  { id: 'the-tommyknockers',            title: 'The Tommyknockers',                   titleEs: 'Los Tommyknockers',                       year: 1987, category: 'novel' },
  { id: 'the-dark-half',                title: 'The Dark Half',                       titleEs: 'La mitad oscura',                         year: 1989, category: 'novel' },
  { id: 'needful-things',               title: 'Needful Things',                      titleEs: 'La tienda',                               year: 1991, category: 'novel' },
  { id: 'geralds-game',                 title: "Gerald's Game",                       titleEs: 'El juego de Gerald',                      year: 1992, category: 'novel' },
  { id: 'dolores-claiborne',            title: 'Dolores Claiborne',                   titleEs: 'Dolores Claiborne',                       year: 1992, category: 'novel' },
  { id: 'insomnia',                     title: 'Insomnia',                            titleEs: 'Insomnia',                                year: 1994, category: 'novel' },
  { id: 'rose-madder',                  title: 'Rose Madder',                         titleEs: 'El retrato de Rose Madder',               year: 1995, category: 'novel' },
  { id: 'the-green-mile',               title: 'The Green Mile',                      titleEs: 'La milla verde',                          year: 1996, category: 'novel' },
  { id: 'desperation',                  title: 'Desperation',                         titleEs: 'Desesperación',                           year: 1996, category: 'novel' },
  { id: 'bag-of-bones',                 title: 'Bag of Bones',                        titleEs: 'Un saco de huesos',                       year: 1998, category: 'novel' },
  { id: 'the-girl-who-loved-tom-gordon',title: 'The Girl Who Loved Tom Gordon',        titleEs: 'La chica que amaba a Tom Gordon',         year: 1999, category: 'novel' },
  { id: 'hearts-in-atlantis',           title: 'Hearts in Atlantis',                  titleEs: 'Corazones en la Atlántida',               year: 1999, category: 'novel' },
  { id: 'dreamcatcher',                 title: 'Dreamcatcher',                        titleEs: 'El cazador de sueños',                    year: 2001, category: 'novel' },
  { id: 'from-a-buick-8',               title: 'From a Buick 8',                      titleEs: 'Buick 8, un coche perverso',              year: 2002, category: 'novel' },
  { id: 'colorado-kid',                 title: 'Colorado Kid',                        titleEs: 'Colorado Kid',                            year: 2005, category: 'novel' },
  { id: 'cell',                         title: 'Cell',                                titleEs: 'Cell',                                    year: 2006, category: 'novel' },
  { id: 'liseys-story',                 title: "Lisey's Story",                       titleEs: 'La historia de Lisey',                    year: 2006, category: 'novel' },
  { id: 'duma-key',                     title: 'Duma Key',                            titleEs: 'Duma Key',                                year: 2008, category: 'novel' },
  { id: 'under-the-dome',               title: 'Under the Dome',                      titleEs: 'La cúpula',                               year: 2009, category: 'novel' },
  { id: '11-22-63',                     title: '11/22/63',                            titleEs: '22/11/63',                                year: 2011, category: 'novel' },
  { id: 'doctor-sleep',                 title: 'Doctor Sleep',                        titleEs: 'Doctor Sueño',                            year: 2013, category: 'novel' },
  { id: 'joyland',                      title: 'Joyland',                             titleEs: 'Joyland',                                 year: 2013, category: 'novel' },
  { id: 'revival',                      title: 'Revival',                             titleEs: 'Revival',                                 year: 2014, category: 'novel' },
  { id: 'sleeping-beauties',            title: 'Sleeping Beauties (con Owen King)',   titleEs: 'Bellas durmientes (con Owen King)',        year: 2017, category: 'novel' },
  { id: 'the-outsider',                 title: 'The Outsider',                        titleEs: 'El visitante',                            year: 2018, category: 'novel' },
  { id: 'elevation',                    title: 'Elevation',                           titleEs: 'Elevación',                               year: 2018, category: 'novel' },
  { id: 'the-institute',                title: 'The Institute',                       titleEs: 'El instituto',                            year: 2019, category: 'novel' },
  { id: 'later',                        title: 'Later',                               titleEs: 'Después',                                 year: 2021, category: 'novel' },
  { id: 'billy-summers',                title: 'Billy Summers',                       titleEs: 'Billy Summers',                           year: 2021, category: 'novel' },
  { id: 'fairy-tale',                   title: 'Fairy Tale',                          titleEs: 'Cuento de hadas',                         year: 2022, category: 'novel' },
  { id: 'holly',                        title: 'Holly',                               titleEs: 'Holly',                                   year: 2023, category: 'novel' },
  { id: 'never-flinch',                 title: 'Never Flinch',                        titleEs: 'No tengas miedo',                         year: 2025, category: 'novel' },

  // Richard Bachman
  { id: 'rage',           title: 'Rage',            titleEs: 'Rabia',             year: 1977, category: 'bachman', note: 'como Richard Bachman' },
  { id: 'the-long-walk',  title: 'The Long Walk',   titleEs: 'La larga marcha',   year: 1979, category: 'bachman', note: 'como Richard Bachman' },
  { id: 'roadwork',       title: 'Roadwork',        titleEs: 'Carretera maldita', year: 1981, category: 'bachman', note: 'como Richard Bachman' },
  { id: 'the-running-man',title: 'The Running Man', titleEs: 'El fugitivo',       year: 1982, category: 'bachman', note: 'como Richard Bachman' },
  { id: 'thinner',        title: 'Thinner',         titleEs: 'Maleficio',         year: 1984, category: 'bachman', note: 'como Richard Bachman' },
  { id: 'the-regulators', title: 'The Regulators',  titleEs: 'Los reguladores',   year: 1996, category: 'bachman', note: 'como Richard Bachman' },
  { id: 'blaze',          title: 'Blaze',           titleEs: 'Blaze',             year: 2007, category: 'bachman', note: 'como Richard Bachman' },

  // La Torre Oscura
  { id: 'dt-1-gunslinger',     title: 'I. The Gunslinger',               titleEs: 'I. El pistolero',                                year: 1982, category: 'dark-tower' },
  { id: 'dt-2-drawing',        title: 'II. The Drawing of the Three',     titleEs: 'II. El dibujo de los tres',                      year: 1987, category: 'dark-tower' },
  { id: 'dt-3-waste-lands',    title: 'III. The Waste Lands',             titleEs: 'III. Las tierras baldías',                       year: 1991, category: 'dark-tower' },
  { id: 'dt-4-wizard-and-glass',title: 'IV. Wizard and Glass',            titleEs: 'IV. Mago y cristal',                             year: 1997, category: 'dark-tower' },
  { id: 'dt-5-wolves',         title: 'V. Wolves of the Calla',           titleEs: 'V. Lobos de la Calla',                           year: 2003, category: 'dark-tower' },
  { id: 'dt-6-song',           title: 'VI. Song of Susannah',             titleEs: 'VI. Canción de Susannah',                        year: 2004, category: 'dark-tower' },
  { id: 'dt-7-dark-tower',     title: 'VII. The Dark Tower',              titleEs: 'VII. La Torre Oscura',                           year: 2004, category: 'dark-tower' },
  { id: 'dt-45-wind',          title: 'IV.5 The Wind Through the Keyhole',titleEs: 'IV.5 El viento a través del ojo de la cerradura',year: 2012, category: 'dark-tower' },

  // Colecciones de cuentos
  { id: 'night-shift',          title: 'Night Shift',              titleEs: 'El umbral de la noche',       year: 1978, category: 'collections' },
  { id: 'different-seasons',    title: 'Different Seasons',        titleEs: 'Las cuatro estaciones',       year: 1982, category: 'collections' },
  { id: 'skeleton-crew',        title: 'Skeleton Crew',            titleEs: 'Historias fantásticas',       year: 1985, category: 'collections' },
  { id: 'four-past-midnight-1', title: 'Four Past Midnight, Vol. 1', titleEs: '2 después de medianoche', year: 1990, category: 'collections', note: 'The Langoliers · Secret Window' },
  { id: 'four-past-midnight-2', title: 'Four Past Midnight, Vol. 2', titleEs: '4 después de medianoche', year: 1990, category: 'collections', note: 'The Library Policeman · The Sun Dog' },
  { id: 'nightmares-dreamscapes',title: 'Nightmares & Dreamscapes',titleEs: 'Pesadillas y alucinaciones',  year: 1993, category: 'collections' },
  { id: 'everythings-eventual', title: "Everything's Eventual",    titleEs: 'Todo es eventual',            year: 2002, category: 'collections' },
  { id: 'just-after-sunset',    title: 'Just After Sunset',        titleEs: 'Después del anochecer',       year: 2008, category: 'collections' },
  { id: 'full-dark-no-stars',   title: 'Full Dark, No Stars',      titleEs: 'Todo oscuro, sin estrellas',  year: 2010, category: 'collections' },
  { id: 'bazaar-of-bad-dreams', title: 'The Bazaar of Bad Dreams', titleEs: 'El bazar de los malos sueños',year: 2015, category: 'collections' },
  { id: 'if-it-bleeds',         title: 'If It Bleeds',             titleEs: 'Si sangra',                   year: 2020, category: 'collections' },
  { id: 'you-like-it-darker',   title: 'You Like It Darker',       titleEs: 'Si te gusta la oscuridad',    year: 2024, category: 'collections' },

  // No Ficción
  { id: 'danse-macabre', title: 'Danse Macabre', titleEs: 'Danza macabra',   year: 1981, category: 'nonfiction' },
  { id: 'on-writing',    title: 'On Writing',    titleEs: 'Mientras escribo',year: 2000, category: 'nonfiction' },

  // Trilogía Bill Hodges
  { id: 'mr-mercedes',    title: 'Mr. Mercedes',    titleEs: 'Mr. Mercedes',    year: 2014, category: 'bill-hodges' },
  { id: 'finders-keepers',title: 'Finders Keepers', titleEs: 'Quien pierde paga',year: 2015, category: 'bill-hodges' },
  { id: 'end-of-watch',   title: 'End of Watch',    titleEs: 'Fin de guardia',  year: 2016, category: 'bill-hodges' },

  // Trilogía Gwendy
  { id: 'gwendy-button-box',   title: "Gwendy's Button Box",    titleEs: 'La caja de botones de Gwendy', year: 2017, category: 'gwendy', note: 'con Richard Chizmar' },
  { id: 'gwendy-magic-feather',title: "Gwendy's Magic Feather", titleEs: 'La pluma mágica de Gwendy',    year: 2019, category: 'gwendy', note: 'con Richard Chizmar' },
  { id: 'gwendy-final-task',   title: "Gwendy's Final Task",    titleEs: 'La última misión de Gwendy',   year: 2022, category: 'gwendy', note: 'con Richard Chizmar' },

  // El Talismán
  { id: 'the-talisman', title: 'The Talisman (con Peter Straub)', titleEs: 'El talismán (con Peter Straub)', year: 1984, category: 'talisman' },
  { id: 'black-house',  title: 'Black House (con Peter Straub)',  titleEs: 'Casa negra (con Peter Straub)',  year: 2001, category: 'talisman' },
].sort((a, b) => a.year - b.year || a.title.localeCompare(b.title))
